# FinFlow Audit Service Configuration

spring:
  application:
    name: finflow-audit-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/finflow
    username: finflow
    password: finflow_dev
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: elastic_dev
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      group-id: finflow-audit-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/finflow

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.satware.finflow: INFO
    org.springframework.kafka: WARN
    org.elasticsearch: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# FinFlow Audit Configuration
finflow:
  audit:
    retention:
      period: 7y
      archive-after: 1y
    integrity:
      algorithm: SHA-256
      verification-enabled: true
    search:
      index-name: finflow-audit
      batch-size: 1000
    reporting:
      formats: [PDF, CSV, JSON]
      max-records: 100000
  
  kafka:
    topics:
      audit-events: finflow.audit.events
      compliance-reports: finflow.audit.reports

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method