apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/replicas.yaml
  - path: patches/image-tags.yaml

# Common labels for all resources in this overlay
commonLabels:
  environment: production

# Common annotations for all resources in this overlay
commonAnnotations:
  note: "Production environment deployment"
