# FinFlow Legacy Adapter Configuration

spring:
  application:
    name: finflow-legacy-adapter
  
  datasource:
    url: jdbc:postgresql://localhost:5432/finflow
    username: finflow
    password: finflow_dev
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      group-id: finflow-legacy-adapter
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.satware.finflow: INFO
    org.springframework.kafka: WARN
    org.springframework.integration: INFO
    org.apache.camel: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# FinFlow Legacy Integration Configuration
finflow:
  legacy:
    systems:
      # Example legacy system configurations
      mainframe:
        type: MAINFRAME
        connection-timeout: 30s
        retry-attempts: 3
        data-format: FIXED_WIDTH
      core-banking:
        type: DATABASE
        connection-timeout: 15s
        retry-attempts: 2
        data-format: SQL
      file-transfer:
        type: FILE_SYSTEM
        base-directory: /data/legacy
        polling-interval: 60s
        data-format: CSV
    
    transformation:
      cache-enabled: true
      validation-enabled: true
      error-handling: CONTINUE_ON_ERROR
    
    synchronization:
      batch-size: 1000
      parallel-processing: true
      conflict-resolution: LATEST_WINS
  
  kafka:
    topics:
      legacy-events: finflow.legacy.events
      transformation-errors: finflow.legacy.errors
      sync-status: finflow.legacy.sync

# Apache Camel Configuration
camel:
  springboot:
    name: finflow-legacy-adapter
    main-run-controller: true
  component:
    file:
      basic-property-binding: true